server:
  port: 8080
  shutdown: graceful

spring:
  main:
    banner-mode: off
  application:
    name: back
  data:
    mongodb:
      uri: mongodb://localhost:2017
      database: back
      auto-index-creation: true
  threads:
    virtual:
      enabled: true